name: Manhunt
version: 3.0
author: Schachi
api-version: 1.18
description: This is a manhunt plugin! This plugin may cause some problems by executing the reload command.
  To solve these problems, just start a new Manhunt by using the runner command and stop it, by using stopManhunt!

main: main.PluginInitializer

commands:
  runner:
    description: runner player1 [player2, ...] - Starts a new Manhunt!
  addHunter:
    description: addHunter [player] - Adds a new hunter to the currently running Manhunt!
  addRunner:
    description: addRunner [player] - Adds a new runner to the currently running Manhunt!
  removePlayer:
    description: removePlayer [player] - Removes a player from the currently running Manhunt!
  compass:
    description: compass - Drops the hunter a new compass, when executing this command!
  heal:
    description: heal [player] - Heals you or another player!
  stopManhunt:
    description: stopManhunt - Stops the currently running Manhunt!
  updateRate:
    description: updateRate [rate] - Shows or defines the number of ticks, until the compasses are updated again!